name: build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 8 * * 5"

permissions:
  contents: write

jobs:
  Warp_Chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Build Script
        run: python3 run.py

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.event_name != 'pull_request'
        with:
          # 使用 Python 脚本中定义的 v$version
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_TAG }}
          body: |
            Automated Build of Chrome Portable.
            Version: ${{ env.RELEASE_TAG }}
            Build Date: ${{ github.event.head_commit.timestamp }}
          draft: false
          prerelease: false
          # 上传固定文件名的 7z 包
          files: ${{ env.ARCHIVE_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}